import { StyleSheet, Platform } from "react-native";
import {
  globals,
  helpers,
  validators,
  colors,
  fonts,
  images,
  sty,
  localize,
} from "../../../../../configs";
const isIphoneXR = helpers.checkIphoneXR();

export const stylex = StyleSheet.create({
  userBox: {
    /*  width: globals.WINDOW_WIDTH/2, 
          borderBottomWidth: 0.5, 
          borderRightColor: colors.light, 
          borderBottomColor: colors.light  */

    ...sty.aCenter,
    borderRadius: 15,
    ...sty.mgB10,
    backgroundColor: "#fff",
    width: globals.WINDOW_WIDTH / 2 - 4,
  },
  userImgWrap: {
    width: globals.WINDOW_WIDTH / 2 - 4,
    ...sty.appBorder,
    overflow: "hidden",
  },
  userBoxImgWrap: {
    width: "100%",
    height: 150,
    overflow: "hidden",
  },
  userBoxImg: {
    width: "auto",
    height: undefined,
    aspectRatio: 1 / 1,
  },
  // userBoxUsername: {
  //     ...sty.tCenter
  // },
  userBoxBtn: {
    ...sty.padV10,
    ...sty.padH15,
  },
  loadingWrap: {
    ...sty.flex1,
    ...sty.jCenter,
    ...sty.aCenter,
    backgroundColor: colors.darkBg,
  },
  closeBtn: {
    position: "absolute",
    top: 35,
    right: 20,
  },
  picsModal: {
    height: globals.WINDOW_HEIGHT,
    backgroundColor: "#000",
    marginTop: -17,
    height: globals.WINDOW_HEIGHT + 19,
  },
  modalHeader: {
    ...sty.fRow,
    ...sty.jSpace,
    ...sty.padH20,
    ...sty.aCenter,
    position: "absolute",
    // top: Platform.OS === "ios" ? 40 : 20,
    top: 27,
    left: 0,
    width: "100%",
    zIndex: 100,
  },
  modalUserImg: {
    height: 40,
    width: 40,
    borderRadius: 100,
    overflow: "hidden",
    marginRight: 10,
  },
  indicatorWrap: {
    ...sty.fRow,
    ...sty.jSpace,
    ...sty.padH10,
    position: "absolute",
    top: 40,
    left: 0,
    width: "100%",
    zIndex: 100,
  },
  indicatorItem: {
    marginHorizontal: 3,
    height: 4,
    backgroundColor: colors.gray,
    flex: 1,
    borderRadius: 5,
    overflow: "hidden",
  },
  indicator: {
    height: 4,
    backgroundColor: "#fff",
  },
  footerWrap: {
    width: "100%",
    height: 60,
    marginTop: -70,
  },
  footerWrapInner: {
    ...sty.jSpace,
    ...sty.fRow,
    ...sty.aEnd,
    height: 40,
    ...sty.padH15,
  },
  footerInputWrap: {
    ...sty.fRow,
    borderWidth: 1,
    borderColor: "#fff",
    borderRadius: 20,
    ...sty.flex1,
    ...sty.padH15,
    ...sty.jSpace,
    ...sty.aCenter,
    marginRight: 15,
  },
  footerInput: {
    color: "#fff",
    ...sty.flex1,
    height: 40,
  },
  footerMore: {
    width: 30,
    ...sty.aEnd,
  },
  footerMore: {
    width: 40,
    ...sty.jCenter,
    ...sty.aEnd,
  },
  videoLoading: {
    position: "absolute",
    top: 0,
    left: 0,
    height: globals.WINDOW_HEIGHT,
    width: globals.WINDOW_WIDTH,
    backgroundColor: colors.darkBg,
    ...sty.jCenter,
    ...sty.aCenter,
    zIndex: 10,
  },
  storyMeta: {
    ...sty.fRow,
    ...sty.jSpace,
    ...sty.aCenter,
    position: "absolute",
    bottom: 20,
    left: 0,
    width: "100%",
  },
});

export const styles = StyleSheet.create({
  // userImg: {
  //     width: '100%',
  //     height:globals.WINDOW_WIDTH / 2 - 4,
  // },
  storyBox1: {
    paddingTop: 5,
    paddingBottom: 5,
    marginRight: 10,
    borderRadius: 5,
    overflow: "hidden",
    width: (globals.WINDOW_WIDTH - 40) / 4,
  },
  userImg: {
    width: "100%",
    height: globals.WINDOW_WIDTH / 4,
    // borderWidth: 2,
    borderColor: "#fff",
    // borderRadius: 100,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    overflow: "hidden",
  },
  userImg4: {
    width: (globals.WINDOW_WIDTH - 40) / 4 - 5, //"100%",
    height: (globals.WINDOW_WIDTH - 40) / 4 - 5,
    // borderWidth: 2,
    borderColor: "#fff",
    borderRadius: ((globals.WINDOW_WIDTH - 40) / 4 - 4) / 2,
    // borderTopRightRadius: 10,
    // borderTopLeftRadius: 10,
    borderWidth: 2,
    overflow: "hidden",
  },
  gradiantWrap: {
    borderRadius: 100,
    borderColor: "#fff",
    // padding: 1.5,
    width: (globals.WINDOW_WIDTH - 40) / 4,
    height: (globals.WINDOW_WIDTH - 40) / 4,
    ...sty.aCenter,
    ...sty.jCenter,
  },
  headerText: {
    color: colors.gray,
    fontWeight: "500",
  },
  storyBox: {
    padding: 10,
    flex: 1,
    flexDirection: "row",
    backgroundColor: "white",
  },
  // userBox: {
  //     ...sty.aCenter,
  //     borderRadius: 15,
  //     ...sty.mgB10,
  //     backgroundColor: '#fff',
  //     width: globals.WINDOW_WIDTH / 2 - 4,
  // },
  userBox: {
    ...sty.aCenter,
    borderRadius: 15,
    marginTop: 5,
    width: globals.WINDOW_WIDTH / 5 - 2,
  },
  imageDim: {
    height: globals.WINDOW_WIDTH / 6,
    width: globals.WINDOW_WIDTH / 6,
  },
  preview: {
    ...sty.w100,
    ...sty.flex1,
    height: globals.WINDOW_HEIGHT,
  },
  // userImgWrap: {
  //     width: globals.WINDOW_WIDTH / 2 - 4,
  //     ...sty.appBorder,
  //     overflow: 'hidden'
  // },
  userImgWrap: {
    height: (globals.WINDOW_WIDTH - 40) / 4 - 3,
    width: (globals.WINDOW_WIDTH - 40) / 4 - 3, //(globals.WINDOW_WIDTH - 40) / 3.5,
    // borderRadius: ((globals.WINDOW_WIDTH - 40) / 4 - 3)/2,
    ...sty.appBorder,
    // borderWidth:1,
    overflow: "hidden",
    ...sty.jCenter,
    ...sty.aCenter,
  },
  uploadImg: {
    height: globals.WINDOW_WIDTH / 18,
    width: globals.WINDOW_WIDTH / 18,
    borderRadius: 100,
    // tintColor : '#fff',
    // backgroundColor : 'blue'
  },
  uploadImgWrap: {
    ...sty.flex1,
    ...sty.aEnd,
    ...sty.jEnd,
    zIndex: 1,
    position: "absolute",
    top: (globals.WINDOW_WIDTH - 40) / 4 - globals.WINDOW_WIDTH / 9 + 20, //(globals.WINDOW_WIDTH - 40) / 4 - globals.WINDOW_WIDTH / 36 + 3,
    left: (globals.WINDOW_WIDTH - 40) / 4 - globals.WINDOW_WIDTH / 17, // (globals.WINDOW_WIDTH - 40) / 4 - globals.WINDOW_WIDTH / 36,
  },
  userBoxImgWrap: {
    width: "100%",
    height: 150,
    overflow: "hidden",
  },
  userBoxImg: {
    width: "auto",
    height: undefined,
    aspectRatio: 1 / 1,
  },
  userBoxUsername: {
    ...sty.tCenter,
    color: "white",
    fontSize: 12,
  },
  userBoxUsernameBlack: {
    ...sty.tCenter,
    color: "black",
    fontSize: 12,
  },
  userBoxBottom: {
    // borderWidth:1.5,
    borderLeftWidth: 1.5,
    borderRightWidth: 1.5,
    borderBottomWidth: 1.5,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  userBoxBtn: {
    ...sty.padV10,
    ...sty.padH15,
  },
  loadingWrap: {
    ...sty.flex1,
    ...sty.jCenter,
    ...sty.aCenter,
    backgroundColor: colors.darkBg,
  },
  closeBtn: {
    position: "absolute",
    top: 35,
    right: 20,
  },
  picsModal: {
    height: globals.WINDOW_HEIGHT,
    backgroundColor: "#000",
    marginTop: -17,
    height: globals.WINDOW_HEIGHT + 19,
  },
  modalHeader: {
    ...sty.fRow,
    ...sty.jSpace,
    ...sty.padH20,
    position: "absolute",
    top: 20,
    left: 0,
    width: "100%",
    zIndex: 100,
  },
  modalUserImg: {
    height: 40,
    width: 40,
    borderRadius: 100,
    overflow: "hidden",
    marginRight: 10,
  },
  indicatorWrap: {
    ...sty.fRow,
    ...sty.jSpace,
    ...sty.padH10,
    position: "absolute",
    top: 40,
    left: 0,
    width: "100%",
    zIndex: 100,
  },
  indicatorItem: {
    marginHorizontal: 3,
    height: 4,
    backgroundColor: colors.gray,
    flex: 1,
    borderRadius: 5,
    overflow: "hidden",
  },
  indicator: {
    height: 4,
    backgroundColor: "#fff",
  },
  footerWrap: {
    width: "100%",
    height: 60,
    marginTop: -70,
  },
  footerWrapInner: {
    ...sty.jSpace,
    ...sty.fRow,
    ...sty.aEnd,
    height: 40,
    ...sty.padH15,
  },
  footerInputWrap: {
    ...sty.fRow,
    borderWidth: 1,
    borderColor: "#fff",
    borderRadius: 20,
    ...sty.flex1,
    ...sty.padH15,
    ...sty.jSpace,
    ...sty.aCenter,
    marginRight: 15,
  },
  inputWrap: {
    // ...sty.pad20,
    // paddingVertical: globals.WINDOW_HEIGHT * 0.01,
    paddingHorizontal: 10,
    backgroundColor: "transparent",
    position: "absolute",
    justifyContent: "center",
    bottom: 15,
    width: "100%",
    zIndex: 10,
  },
  footerInput: {
    color: "#fff",
    ...sty.flex1,
    height: 40,
  },
  footerMore: {
    width: 30,
    ...sty.aEnd,
  },
  footerMore: {
    width: 40,
    ...sty.jCenter,
    ...sty.aEnd,
  },
  videoLoading: {
    position: "absolute",
    top: 0,
    left: 0,
    height: globals.WINDOW_HEIGHT,
    width: globals.WINDOW_WIDTH,
    backgroundColor: colors.darkBg,
    ...sty.jCenter,
    ...sty.aCenter,
    zIndex: 10,
  },
  storyMeta: {
    ...sty.fRow,
    ...sty.jSpace,
    position: "absolute",
    bottom: 10,
    left: 0,
    width: "100%",
    paddingHorizontal: 30,
    zIndex: 1000,
  },
  descMeta: {
    ...sty.fRow,
    position: "absolute",
    width: "100%",
    bottom: 10,
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 30,
  },
  videoError: {
    width: "100%",
    height: globals.WINDOW_WIDTH / (16 / 9),
    backgroundColor: colors.darkBg,
    ...sty.jCenter,
    ...sty.aCenter,
  },
});
