export const images = {
  logo: require("../../assets/images/Home/logo.png"),
  PicstaLogoBlack: require("../../assets/images/Icons/PicstaLogoBlack.png"),
  logoTransparent: require("../../assets/images/Home/logoTransparent.png"),
  user: require("../../assets/images/user.jpg"),
  P_Logo: require("../../assets/images/512_FINAL.jpg"),
  logoUrl: "../../assets/images/Home/logo.png",
  iconSmall: require("../../assets/images/Home/iconSmall.png"),
  icon192x: require("../../assets/images/icon192x.png"),
  thumb: require("../../assets/images/thumb.png"),
  emptyData: require("../../assets/images/emptyData.png"),
  emptyList: require("../../assets/images/emptyList.png"),
  uploadImage: require("../../assets/images/uploadImage.png"),
  uploadVideo: require("../../assets/images/uploadVideo.png"),
  loadingMedia: require("../../assets/images/loadingMedia.png"),
  pointsInfo: require("../../assets/images/info.png"),
  iconSearch: require("../../assets/images/Icons/Serch.png"),
  iconSearchGrey: require("../../assets/images/Icons/iconSearchGrey.png"),
  calendar: require("../../assets/images/Calendar.png"),
  description: require("../../assets/images/Describtion.png"),
  diamond: require("../../assets/images/DIAMOND.png"),
  instaGram: require("../../assets/images/INSTA.png"),
  job: require("../../assets/images/Job.png"),
  light: require("../../assets/images/Light.png"),
  link: require("../../assets/images/LINK.png"),
  location: require("../../assets/images/Location.png"),
  msgIcon: require("../../assets/images/Message.png"),
  phone: require("../../assets/images/PHONE.png"),
  pin: require("../../assets/images/PIN.png"),
  share_post: require("../../assets/images/SHARE.png"),
  //cat
  fashion: require("../../assets/images/categories/Fashion.jpg"),
  art: require("../../assets/images/categories/art.jpg"),
  entertainment: require("../../assets/images/categories/Entertainment.jpg"),
  food: require("../../assets/images/categories/Foodporn.jpg"),
  photography: require("../../assets/images/categories/Photography.jpg"),
  sports: require("../../assets/images/categories/sports.jpg"),
  notification_empty: require("../../assets/images/notification_empty.jpg"),
  news_feed: require("../../assets/images/NEWSFEED.png"),
  //Social
  facebook: require("../../assets/images/Social/FBIcon.png"),
  fbicon: require("../../assets/images/Social/FBIcon.png"),
  fbicon1: require("../../assets/images/Social/FBIcon1.png"),
  // fbicon2: require('../../assets/images/Social/FBIcon2.png'),
  instagram: require("../../assets/images/Social/Instagram.png"),
  youtube: require("../../assets/images/Social/Youtube.png"),
  linkedin: require("../../assets/images/Social/Linkedin.png"),
  twitter: require("../../assets/images/Social/Twitter.png"),
  tumblr: require("../../assets/images/Social/Tumblr.png"),
  pintrest: require("../../assets/images/Social/Pintrest.png"),
  google_plus: require("../../assets/images/Social/google_plus.png"),
  whatsapp: require("../../assets/images/Social/whatsapp.png"),
  email: require("../../assets/images/Social/Email.png"),
  mail: require("../../assets/images/Social/mail.png"),
  facebooklogo: require("../../assets/images/Social/Facebook.png"),
  googlelogo: require("../../assets/images/Social/Google.png"),
  facebook_share: require("../../assets/images/Social/facebook_share.png"),
  mail_share: require("../../assets/images/Social/mail_share.png"),
  story_share: require("../../assets/images/Social/story_share.png"),

  //Loader
  loaderImg1: require("../../assets/images/Loader/logo1.png"),
  loaderImg2: require("../../assets/images/Loader/logo2.png"),

  //Tab
  // campaign: require("../../assets/images/tab/campaign.png"),
  // campaignB: require("../../assets/images/tab/campaignB.png"),
  // home: require("../../assets/images/tab/home.png"),
  // homeB: require("../../assets/images/tab/homeB.png"),
  // notification: require("../../assets/images/tab/notification.png"),
  // notificationB: require("../../assets/images/tab/notificationB.png"),
  // participant: require("../../assets/images/tab/participant.png"),
  // participantB: require("../../assets/images/tab/participantB.png"),
  // profile: require("../../assets/images/tab/profile.png"),
  // profileB: require("../../assets/images/tab/profileB.png"),
  // upload: require("../../assets/images/tab/upload.png"),
  // uploadB: require("../../assets/images/tab/uploadB.png"),
  campaign: require("../../assets/images/tab/Trohphy1.png"),
  campaignB: require("../../assets/images/tab/TROPHY_FILLED.png"),
  home: require("../../assets/images/tab/HOME_BLACK.png"),
  homeB: require("../../assets/images/tab/HOME_FILLED.png"),
  notification: require("../../assets/images/tab/star.png"),
  notificationB: require("../../assets/images/tab/STAR_FILLED.png"),
  participant: require("../../assets/images/tab/participant.png"),
  participantB: require("../../assets/images/tab/participantB.png"),
  profile: require("../../assets/images/tab/profile1.png"),
  profileB: require("../../assets/images/tab/PROFILE2.png"),
  upload: require("../../assets/images/tab/plus.png"),
  uploadB: require("../../assets/images/tab/plus.png"),
  newUpload: require("../../assets/images/tab/NewPlus.png"),
  newUploadB: require("../../assets/images/tab/NewPlus.png"),
  newUploadBold: require("../../assets/images/tab/uploadNew.png"),
  home1: require("../../assets/images/tab/explore-stripe.png"),
  homeB1: require("../../assets/images/tab/explore-solid.png"),
  campaign1: require("../../assets/images/tab/home_grey.png"),
  campaignB1: require("../../assets/images/tab/home_colored.png"),
  trofy1: require("../../assets/images/tab/campaign1.png"),
  trofyB1: require("../../assets/images/tab/campaign12.png"),

  campaign3: require("../../assets/images/tab/home_grey.png"),
  notification1: require("../../assets/images/tab/notification1.png"),
  notificationB1: require("../../assets/images/tab/notificationB1.png"),
  messageIcon1: require("../../assets/images/tab/message1.png"),
  messageIconB1: require("../../assets/images/tab/messageB1.png"),
  lap: require("../../assets/images/tab/laptop.png"),
  lapB1: require("../../assets/images/tab/laptopBlack.png"),

  //Icons
  smiley: require("../../assets/images/Icons/Simley.png"),
  // comment: require("../../assets/images/Icons/comment.png"),
  comment: require("../../assets/images/Icons/COMMENTS.png"),
  // heart: require("../../assets/images/Icons/heart.png"),
  // heartDark: require("../../assets/images/Icons/heartDark.png"),
  heart: require("../../assets/images/Icons/LIKEBUTTON1.png"),
  heartDark: require("../../assets/images/Icons/LIKEBUTTON.png"),
  unlike: require("../../assets/images/Icons/UNLIKEBUTTON_UPDATED.png"),
  likeBtn: require("../../assets/images/Icons/LIKEBUTTON_UPDATED.png"),
  // share: require("../../assets/images/Icons/share.png"),
  share: require("../../assets/images/Icons/Share1.png"),
  threeDots: require("../../assets/images/Icons/Threedots1.png"),
  filter: require("../../assets/images/Icons/filter.png"),
  empty_users: require("../../assets/images/emptyUsers.jpg"),
  jobs: require("../../assets/images/jobs.jpg"),

  // threeDots: require("../../assets/images/Icons/threeDots.png"),
  threeDot: require("../../assets/images/Icons/threeDot.png"),
  shareWhite: require("../../assets/images/Icons/shareWhite.png"),
  search: require("../../assets/images/Icons/search.png"),
  searchBlack: require("../../assets/images/Icons/SearchBlack.png"),
  searchBlack1: require("../../assets/images/Icons/SearchBlack.png"),
  trophy: require("../../assets/images/Icons/trophy.png"),
  trophyBlack: require("../../assets/images/Icons/trophyBlack.png"),

  users: require("../../assets/images/Icons/user.png"),
  play: require("../../assets/images/Icons/play.png"),
  clock: require("../../assets/images/Icons/clock.png"),
  closeContest: require("../../assets/images/Icons/closeContest.png"),
  message: require("../../assets/images/Icons/message.png"),
  messageBlack: require("../../assets/images/Icons/MessageBlack.png"),
  messageWhite: require("../../assets/images/Icons/MessageWhite.png"),

  story: require("../../assets/images/Icons/story.png"),
  uploadStory: require("../../assets/images/Icons/uploadStory.png"),
  blog: require("../../assets/images/Icons/blog.png"),
  menu: require("../../assets/images/Icons/menu.png"),
  writeMessage: require("../../assets/images/Icons/writeMessage.png"),
  writeMessage1: require("../../assets/images/Icons/writeMessage1.png"),
  leftBackArrow: require("../../assets/images/Icons/LeftBlackArrow.png"),
  leftBackWhiteArrow: require("../../assets/images/Icons/leftBackArrow.png"),
  leftWhite: require("../../assets/images/Icons/Left.png"),

  setting: require("../../assets/images/Icons/setting.png"),
  profileSetting: require("../../assets/images/Icons/setting1.png"),
  termsAndCondition: require("../../assets/images/Icons/terms.png"),
  shareArrow: require("../../assets/images/Icons/arrow.png"),
  shareArrowBlack: require("../../assets/images/Icons/shareBlack.png"),

  refresh: require("../../assets/images/Icons/Refresh.png"),
  termsCake: require("../../assets/images/Icons/terms_cake.png"),
  termsCamera: require("../../assets/images/Icons/terms_camera.png"),
  termsClock: require("../../assets/images/Icons/terms_clock.png"),
  termsClose: require("../../assets/images/Icons/terms_close.png"),
  termsCopyright: require("../../assets/images/Icons/terms_copyright.png"),
  termsDelete: require("../../assets/images/Icons/terms_delete.png"),
  termsMail: require("../../assets/images/Icons/terms_mail.png"),
  termsNo: require("../../assets/images/Icons/terms_no.png"),
  termsNumber: require("../../assets/images/Icons/terms_number.png"),
  termsPin: require("../../assets/images/Icons/terms_pin.png"),
  termsTrophie: require("../../assets/images/Icons/terms_trophie.png"),
  terms_user: require("../../assets/images/Icons/terms_user.png"),
  news: require("../../assets/images/Icons/news.png"),
  correctTick: require("../../assets/images/Icons/correctTick.png"),
  verifiedUser: require("../../assets/images/Icons/verified_user.png"),
  loginButton: require("../../assets/images/Icons/login.png"),
  tabDots: require("../../assets/images/Icons/tabDots.png"),
  setting_profile: require("../../assets/images/Icons/setting_profile.png"),
  setting_info: require("../../assets/images/Icons/setting_info.png"),
  setting_logout: require("../../assets/images/Icons/setting_logout.png"),
  setting_privacy: require("../../assets/images/Icons/setting_privacy.png"),
  setting_service: require("../../assets/images/Icons/setting_service.png"),
  setting_lan: require("../../assets/images/Icons/setting_language.png"),
  fbButton: require("../../assets/images/Icons/fbButton.png"),
  fblogo: require("../../assets/images/Icons/fbButtonLogo.png"),
  applelogo: require("../../assets/images/Icons/appleButtonLogo.png"),
  info: require("../../assets/images/Icons/INFO_BLACK.png"),
  saved: require("../../assets/images/Icons/bookmark.png"),
  grid: require("../../assets/images/Icons/grid.png"),
  //Temp
  // nature: require("../../assets/images/temp/nature.jpeg"),
  // employee: require("../../assets/images/temp/Employee.jpg"),
  // post: require("../../assets/images/temp/Post.jpg"),
  gallery: require("../../assets/images/temp/gallery.png"),
  star: require("../../assets/images/temp/star.png"),
  // envelope: require("../../assets/images/temp/envelope.png"),

  //contest
  bottomBar: require("../../assets/images/gradient.png"),

  //Home
  homeNews: require("../../assets/images/Home/home_news.png"),
  homeExplore: require("../../assets/images/Home/home_explore.png"),
  homeStage: require("../../assets/images/Home/home_stage.png"),
  homePlus: require("../../assets/images/Home/plus.png"),
  gridVideo: require("../../assets/images/Home/gridVideo.png"),
  gridStages: require("../../assets/images/Home/gridStages.png"),
  gridBlog: require("../../assets/images/Home/gridBlog.png"),
  newVideo:require('../../assets/images/videoEdited.png'),
  //Intro
  // intro1en: require("../../assets/images/temp/intro1en.png"),
  // intro2en: require("../../assets/images/temp/intro2.png"),
  // intro3en: require("../../assets/images/temp/intro3en.png"),
  // intro1he: require("../../assets/images/temp/intro1he.png"),
  // intro2he: require("../../assets/images/temp/intro2.png"),
  // intro3he: require("../../assets/images/temp/intro3he.png")

  // intro1en: require("../../assets/images/temp/intr1.png"),
  // intro2en: require("../../assets/images/temp/intr2.png"),
  // intro3en: require("../../assets/images/temp/intr3.png"),
  // intro1he: require("../../assets/images/temp/intr1.png"),
  // intro2he: require("../../assets/images/temp/intr2.png"),
  // intro3he: require("../../assets/images/temp/intr3.png"),

  // bgIntro1: require("../../assets/images/temp/bgIntro1.png"),
  // bgIntro2: require("../../assets/images/temp/bgIntro2.png"),
  // bgIntro3: require("../../assets/images/temp/bgIntro3.png"),
  // bgIntro4: require("../../assets/images/temp/bgIntro4.png"),
  // bgIntro5: require("../../assets/images/temp/bgIntro5.png"),

  //contest
  arrowDown: require("../../assets/images/Icons/ArrowDown.png"),
  arrowLeft: require("../../assets/images/Icons/ArrowLeft.png"),
  //How to win
  ResInsta: require("../../assets/images/Icons/ResInsta.png"),
  VotePhoto: require("../../assets/images/Icons/VotePhoto.png"),
  RunningTime: require("../../assets/images/Icons/RunningTime.png"),
  OrgContest: require("../../assets/images/Icons/OrgContest.png"),
  Organisers: require("../../assets/images/Icons/Organisers.png"),
  TermsCondition: require("../../assets/images/Icons/TermsCondition.png"),
  ContestFinalist: require("../../assets/images/Icons/ContestFinalist.png"),
  finalistAnnounce: require("../../assets/images/Icons/finalistAnnounce.png"),
  MsgSend: require("../../assets/images/Icons/MsgSend.png"),

  infoContest: require("../../assets/images/Icons/InfoContest.png"),
  gridContest: require("../../assets/images/Icons/GridContest.png"),
  finalistContest: require("../../assets/images/Icons/FinalistContest.png"),
  // winnerContest: require("../../assets/images/Icons/WinnerContest.png"),

  //contest Full View
  youTube1: require("../../assets/images/Icons/youTube.png"),
  fb: require("../../assets/images/Icons/fb.png"),
  insta: require("../../assets/images/Icons/insta.png"),
  whatsup: require("../../assets/images/Icons/whatsup.png"),
  newsfeed: require("../../assets/images/Icons/newsfeed.png"),
  Group8: require("../../assets/images/Icons/Group8.png"),
  tiktok: require("../../assets/images/Icons/tiktok.png"),
  rateApp: require("../../assets/images/rate.png"),
  followUS: require("../../assets/images/followonInsta.png"),
  contactUS: require("../../assets/images/contactUs.png"),
};
