import { StyleSheet } from "react-native";
import {  fonts, sty, colors } from "../../../configs";
import { Dimensions, Platform } from "react-native";

export const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
  },
  bottomContainer: {
    position: "absolute",
    top: '55%',
    flex: 1,
    alignSelf: "center",
  },
  logoImgWrap: {
    height: Dimensions.get("window").height / 5,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
  },
  logoImg: {
    height: 100,
    width: "70%",
  },
  logoIntro1: {
    height: 60,
    width: Dimensions.get("window").width - 80,
  },
  xrLogoImg: {
    marginTop:30,
  },
  slideWrap: {
    flex: 1,
  },
  slideWrapText: {
    width: "100%",
    alignItems: "center",
  },
  slideTxt1: {
    fontSize: 17, //18,
    color: "white", //"black",
    fontWeight: "400",
    textAlign: "center",
    lineHeight: 22,
  },
  slideTxt: {
    fontSize: 20,
    color: "black",
    fontWeight: "bold",
    textAlign: "center",
    lineHeight: 25,
  },
  registerBtn: {
    backgroundColor: "transparent",
    padding: 3,
    borderColor: "#fff",
    borderWidth: 2,
    marginVertical:5,
    borderRadius: 5,
    overflow: "hidden",
    marginHorizontal: 30,
  },
  registerBtn1: {
    backgroundColor: "transparent",
    padding: 3,
    borderColor: "#fff",
    marginVertical:15,
    borderRadius: 5,
    overflow: "hidden",
  },
  fbBtn: {
    backgroundColor: "#3F51B5",
    padding: 3,
    borderColor: "#3F51B5",
    // borderWidth: 2,
    marginVertical:5,
    borderRadius: 5,
    overflow: "hidden",
    marginHorizontal: 30,
  },
  registerBtnTxt: {
    fontWeight: "bold",
    color: "#fff",
    fontSize: 18,
    paddingVertical:5,
  },
  loginBtn: {
    padding: 0,
    borderColor: "#fff",
    borderWidth: 2,
    borderRadius: 5,
    overflow: "hidden",
  },
  xrLoginBtn: {
    marginBottom:20,
  },
  loginBtnTxt: {
    fontWeight: "bold",
    color: colors.black,
    fontSize: 18,
    paddingVertical:5,
  },
  circleWrap: {
    flexDirection: "row" ,
    paddingVertical: 20 ,
    paddingHorizontal: 20 ,
    justifyContent: "center",
  },
  btnWrap: {
    borderWidth: 1,
    borderColor: "white",
    borderRadius: 5,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  textWrap: {
    flex: 0.7,
    justifyContent: "center",
    paddingLeft: 5,
  },
  circle: {
    height: 8,
    width: 8,
    marginRight: 7,
    backgroundColor: "#fff",
    borderRadius: 100,
  },
  tabWrap: {
    flex: 1,
  },
  facebookBtn: {
    borderRadius: 5,
    borderColor: "#808080",
    overflow: "hidden",
    backgroundColor: "#4267B2",
    padding: 3,
    borderColor: "#fff",
    borderWidth: 0,
    marginVertical:5,
    borderRadius: 5,
    marginTop:30,
    alignItems: "center",
  },
  appleBtn: {
    backgroundColor: "#FFF",
    borderRadius: 5,
    width: Dimensions.get("window").width - 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 15,
    height: 40,
    alignSelf: "center",
  },
  transparentBtn: {
    backgroundColor: "rgba(255, 255, 255, 0.4)",
    borderRadius: 5,
    width: Dimensions.get("window").width - 60,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 15,
    height: 40,
  },
  socialIcon: {
    height: 25,
    width: 25,
    alignSelf: "center",
    position: "absolute",
    left: 15,
  },
  socialText: {
    color:colors.black,
    textAlign: "center",
    fontSize: 16,
    fontWeight: "700",
  },
  socialTextWhite: {
    textAlign: "center",
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  termsTxt: {
    textAlign: "center",
    fontSize: 16,
    fontWeight: "bold",
    color: "#FFFFFF",
    paddingVertical: 3,
  },
  subtitle: {
    textAlign: "center",
    fontSize: 15,
    color: "#FFFFFF",
    paddingVertical: 5,
    fontWeight:'500',
    lineHeight:20,
    textAlign: "left",
    paddingBottom:16,
    paddingHorizontal: 10,

  },
  title: {
    textAlign: "center",
    fontSize: 42,
    lineHeight: 45,
    fontWeight:'bold',
    color: "#FFFFFF",
    paddingBottom: 5,
    textAlign: "justify",
    paddingHorizontal: 10,
    paddingTop:10
  },
  termsLink: {
    textAlign: "center",
    fontSize: 12,
    color: "#FFFFFF",
    paddingBottom: 15,
  },
});
