import { StyleSheet } from "react-native";
import { globals, fonts, sty, colors } from "../../../configs";

export const styles = StyleSheet.create({
  wrapper: {
    ...sty.flex1,
  },
  bottomContainer: {
    position:globals.WINDOW_HEIGHT>690 ?"absolute":'relative',
    bottom: globals.WINDOW_HEIGHT>690 ?30:0,
    width: "90%",
    alignSelf: "center",
    marginBottom:10
  },
  appLogo: {
    height: 35,
    width: 35,
  },
  subtitle: {
    ...sty.tCenter,
    fontSize: fonts.small,
    color: colors.black,
    paddingVertical: 10,
    textAlign: "left",
    paddingHorizontal: 12,
  },
  title: {
    ...sty.tCenter,
    fontSize: fonts.large,
    fontWeight: "bold",
    color: colors.black,
    paddingTop: 10,
    textAlign: "justify",
    paddingHorizontal: 12,
  },
  imgWrap: {
    backgroundColor: colors.white,
    shadowOffset: { height: 1, width: 1 },
    shadowOpacity: 0.5,
    elevation: 2,
    margin: 10,
    borderRadius: 30,
    height: 50,
    width: 50,
    marginTop: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  headerView: {
    width: "100%",
    height: 40,
    flexDirection: "row",
    borderBottomColor: colors.black,
    borderBottomWidth: 0.5,
    alignItems: "center",
    paddingHorizontal: 16,
  },
  logoImgWrap: {
    height: globals.WINDOW_HEIGHT / 5,
    ...sty.jCenter,
    ...sty.aCenter,
    marginTop: 30,
  },
  logoImg: {
    height: 100,
    width: "70%",
  },
  logoIntro1: {
    height: 60,
    width: globals.WINDOW_WIDTH - 80,
  },
  xrLogoImg: {
    ...sty.mgT30,
  },
  slideWrap: {
    ...sty.flex1,
  },
  slideWrapText: {
    width: "100%",
    ...sty.aCenter,
  },
  slideTxt1: {
    fontSize: 17, //18,
    // color: "white", //"black",
    color:colors.black,
    fontWeight: "400",
    textAlign: "center",
    lineHeight: 22,
  },
  slideTxt: {
    fontSize: 20,
    color: "black",
    fontWeight: "bold",
    textAlign: "center",
    lineHeight: 25,
  },
  registerBtn: {
    backgroundColor: "transparent",
    padding: 3,
    borderColor: "#fff",
    borderWidth: 2,
    ...sty.mgV5,
    borderRadius: 5,
    overflow: "hidden",
    marginHorizontal: 30,
  },
  registerBtn1: {
    backgroundColor: "transparent",
    padding: 3,
    borderColor: "#fff",
    ...sty.mgV15,
    borderRadius: 5,
    overflow: "hidden",
  },
  fbBtn: {
    backgroundColor: "#3F51B5",
    padding: 3,
    borderColor: "#3F51B5",
    // borderWidth: 2,
    ...sty.mgV5,
    borderRadius: 5,
    overflow: "hidden",
    marginHorizontal: 30,
  },
  registerBtnTxt: {
    fontWeight: "bold",
    color: "#fff",
    fontSize: fonts.medium,
    ...sty.padV5,
  },
  loginBtn: {
    padding: 0,
    borderColor: "#fff",
    borderWidth: 2,
    borderRadius: 5,
    overflow: "hidden",
  },
  xrLoginBtn: {
    ...sty.mgB20,
  },
  loginBtnTxt: {
    fontWeight: "bold",
    color: "#fff",
    fontSize: fonts.medium,
    ...sty.padV5,
  },
  circleWrap: {
    ...sty.fRow,
    ...sty.padV10,
    ...sty.padH20,
    ...sty.jCenter,
  },
  btnWrap: {
    borderWidth: 1,
    borderColor: "white",
    borderRadius: 5,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  textWrap: {
    flex: 0.7,
    justifyContent: "center",
    paddingLeft: 5,
  },
  circle: {
    height: 8,
    width: 8,
    marginRight: 7,
    backgroundColor: "#fff",
    borderRadius: 100,
  },
  tabWrap: {
    ...sty.flex1,
  },
  facebookBtn: {
    ...sty.appBorder,
    overflow: "hidden",
    backgroundColor: "#4267B2",
    padding: 3,
    borderColor: "#fff",
    borderWidth: 0,
    ...sty.mgV5,
    borderRadius: 5,
    ...sty.mgT30,
    ...sty.aCenter,
  },
  appleBtn: {
    backgroundColor: "#FFF",
    borderRadius: 5,
    width: globals.WINDOW_WIDTH - 60,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 15,
    height: 40,
  },
  transparentBtn: {
    backgroundColor: "rgba(255, 255, 255, 0.4)",
    borderRadius: 5,
    width: globals.WINDOW_WIDTH - 60,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 15,
    height: 40,
  },
  socialIcon: {
    height: 25,
    width: 25,
    alignSelf: "center",
    position: "absolute",
    left: 15,
  },
  socialText: {
    ...sty.tCenter,
    color:colors.black,
    fontSize: fonts.small,
    fontWeight: "700",
  },
  socialTextWhite: {
    ...sty.tCenter,
    fontSize: fonts.small,
    fontWeight: "700",
    color: colors.white,
  },
  termsTxt: {
    ...sty.tCenter,
    fontSize: fonts.small,
    fontWeight: "bold",
    color: colors.black,
    paddingVertical: 3,
  },
  termsTxtOld: {
    ...sty.tCenter,
    fontSize: fonts.xxSmall,
    color: colors.black,
    paddingVertical: 8,
  },
  termsLink: {
    ...sty.tCenter,
    fontSize: fonts.xxSmall,
    color: colors.black,
    fontWeight: "bold",
    paddingBottom: 15,
  },
});
