import { StyleSheet } from "react-native";
import {
  globals,
  helpers,
  validators,
  colors,
  fonts,
  images,
  sty,
  localize,
} from "../../../../../configs";

export const styles = StyleSheet.create({
  postImgWrap: {
    ...sty.flex1,
    ...sty.jCenter,
    ...sty.aCenter,
  },
  uploadPromptWrap: {
    ...sty.flex1,
    ...sty.jCenter,
    ...sty.aCenter,
  },
  video: {
    width: globals.WINDOW_WIDTH,
    height: "100%",
    // flex: 1,
  },
  uploadPromptInner: {
    borderRadius: 150,
    backgroundColor: "#f5f5f5",
    overflow: "hidden",
    height: 190,
    width: 190,
    ...sty.jCenter,
    ...sty.aCenter,
    shadowColor: "#333",
    shadowOpacity: 0.9,
    shadowRadius: 10,
  },
  videoPreview: {
    ...sty.flex1,
    ...sty.jCenter,
    ...sty.aCenter,
  },
  videoTopControls: {
    ...sty.w100,
    ...sty.padV10,
    ...sty.fRow,
    ...sty.jSpace,
    ...sty.padH20,
    ...sty.padT25,
    backgroundColor: "#000",
    height: 70,
  },
  videoTopLeftControls: {
    ...sty.flex1,
  },
  videoTopRightControls: {
    ...sty.flex1,
    ...sty.aEnd,
  },
  bottomControls: {
    ...sty.w100,
    ...sty.padV10,
    ...sty.fRow,
    ...sty.jSpace,
    ...sty.aCenter,
    ...sty.padH20,
    backgroundColor: "#000",
    height: 70,
  },
  leftControls: {},
  centerControls: {
    ...sty.fRow,
    height: 40,
  },
  captureWrap: {
    borderWidth: 1,
    borderColor: "#fff",
    ...sty.fRow,
    borderRadius: 20,
  },
  captureVideoView: {
    borderRightWidth: 1,
    borderRightColor: "#fff",
    ...sty.aCenter,
    ...sty.jCenter,
    ...sty.padH20,
  },
  captureImgView: {
    ...sty.aCenter,
    ...sty.padH20,
    ...sty.padV5,
    ...sty.jCenter,
  },
  rightControls: {},
  uploadAgainWrap: {
    ...sty.fRow,
    position: "absolute",
    top: 80,
    right: 10,
    height: 60,
    width: 60,
    borderRadius: 100,
    backgroundColor: "#fff",
    shadowColor: "#333",
    shadowOpacity: 0.3,
    shadowRadius: 10,
    zIndex: 1000,
    ...sty.jCenter,
    ...sty.aCenter,
  },
  uploadWrap: {
    ...sty.flex1,
    backgroundColor: "#fff",
  },
  uploadItem: {
    ...sty.pad20,
    ...sty.flex1,
    borderWidth: 2,
    borderColor: colors.appBg,
    ...sty.jCenter,
    ...sty.aCenter,
    overflow: "hidden",
    borderRadius: 5,
  },
  uploadMediaTxt: {
    color: "#4a4a4a",
    fontSize: 20,
    fontWeight: "500",
    ...sty.aStart,
    position: "absolute",
    bottom: 20,
  },
  uploadMedia: {
    height: 100,
    width: 100,
  },
});
